Repository EXG1O/Constructor-Telegram-Bots, pull requests merged in 2025-02, with the labels that each got.

#134 Add `django-admin-sortable2` for easily change order of some models
  constructor_telegram_bots/settings.py
  donation/admin.py
  donation/migrations/0001_initial.py
  donation/migrations/0002_alter_method_position_alter_section_position.py
  donation/models.py
  instruction/admin.py
  instruction/migrations/0001_initial.py
  instruction/migrations/0002_alter_section_position.py
  instruction/models.py
  poetry.lock
  privacy_policy/admin.py
  privacy_policy/migrations/0001_initial.py
  privacy_policy/migrations/0002_alter_section_position.py
  privacy_policy/models.py
  pyproject.toml
Labels: dependencies, enhancement

#135 Create new `PublicURLField` field
  constructor_telegram_bots/fields.py
  constructor_telegram_bots/validators.py
  donation/migrations/0003_alter_method_link.py
  donation/models.py
  telegram_bots/base_models.py
  telegram_bots/migrations/0002_alter_backgroundtaskapirequest_url_and_more.py
  telegram_bots/models.py
Labels: feature

#137 Fix `is_enabled` admin field of `TelegramBot` model
  telegram_bots/admin.py
Labels: bug

#138 Fix `TelegramBotsHubManager` model manager
  telegram_bots/hub/models.py
  telegram_bots/tasks.py
Labels: bug

#140 Fix `CommandSerializer.update_keyboard` method
  telegram_bots/serializers.py
Labels: bug

#141 Disable client-side cache for dynamic content
  donation/views.py
  instruction/views.py
  privacy_policy/views.py
  updates/views.py
Labels: bug

#142 Fix `BaseToken.user` property
  users/authentication.py
  users/tokens.py
  users/views.py
Labels: bug

#144 Fix `get_freest` method of `TelegramBotsHub` model manager
  telegram_bots/hub/models.py
Labels: bug

#145 Update admin fields for `TelegramBot` model
  locale/en/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  telegram_bots/admin.py
Labels: bug, enhancement

#146 Add `__str__` magic method to `TelegramBotsHub` model
  telegram_bots/hub/models.py
Labels: bug

#147 Add `LOGS_DIR` setting to django settings
  constructor_telegram_bots/gunicorn.py
  constructor_telegram_bots/settings.py
Labels: feature

#149 Upgrade `gunicorn` config
  constructor_telegram_bots/gunicorn.py
Labels: enhancement, refactor, typing

#148 Upgrade typing for django settings
  .github/workflows/main.yml
  constructor_telegram_bots/settings.py
Labels: enhancement, refactor, typing
